### ISSUE TITLE
ImportError: cannot import name 'MediaPlayerEntity' 

### ISSUE THREAD

**Issue by jlucasgithub** [nstrelow/ha_philips_android_tv#40]
Hi

After update, component doesn't work with Home Assistant 0.109.6...
Is there a simple way to make it work again?

Thanks

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 777, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 279, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/philips_android_tv/media_player.py", line 9, in <module>
    from homeassistant.components.media_player import (
ImportError: cannot import name 'MediaPlayerEntity' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py)

**Comment by olbjan** [comment]
Easy: Update to HA 0.110

**Comment by nstrelow** [comment]
As @olbjan said, please update to HA 0.110.
https://www.home-assistant.io/blog/2020/05/20/release-110/
